# Generated by Django 4.2.1 on 2023-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0002_songdatac_songdatao_delete_songdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDataB2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_kisyu', models.CharField(max_length=30)),
                ('game_no', models.CharField(max_length=30)),
                ('game_player', models.CharField(max_length=100)),
                ('game_kadai1', models.CharField(max_length=50)),
                ('game_kadai2', models.CharField(max_length=50)),
                ('game_kadai3', models.CharField(max_length=50)),
            ],
        ),
    ]
