# Generated by Django 4.2.1 on 2023-08-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0003_gamedatab2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdatac',
            name='fumen_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songdatao',
            name='fumen_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
