# Generated by Django 4.2.1 on 2024-07-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0004_songdatac_fumen_id_songdatao_fumen_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongDataCN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_official_id', models.CharField(max_length=10, unique=True)),
                ('song_name', models.CharField(max_length=100)),
                ('song_reading', models.CharField(max_length=100)),
                ('song_artist', models.CharField(max_length=100)),
                ('song_genre', models.CharField(max_length=20)),
                ('song_bpm', models.IntegerField(null=True)),
                ('song_bpm_nodata', models.BooleanField()),
                ('song_release', models.DateField()),
                ('song_image_url', models.CharField(max_length=100)),
                ('song_fumen_id', models.CharField(max_length=10, null=True, unique=True)),
                ('is_worldsend', models.BooleanField()),
                ('has_ultima', models.BooleanField()),
                ('only_ultima', models.BooleanField()),
                ('exp_const', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('exp_const_nodata', models.BooleanField()),
                ('exp_notes', models.IntegerField(null=True)),
                ('exp_notes_nodata', models.BooleanField()),
                ('exp_notesdesigner', models.CharField(max_length=100, null=True)),
                ('exp_notesdesigner_nodata', models.BooleanField()),
                ('mas_const', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('mas_const_nodata', models.BooleanField()),
                ('mas_notes', models.IntegerField(null=True)),
                ('mas_notes_nodata', models.BooleanField()),
                ('mas_notesdesigner', models.CharField(max_length=100, null=True)),
                ('mas_notesdesigner_nodata', models.BooleanField()),
                ('ult_const', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('ult_const_nodata', models.BooleanField(null=True)),
                ('ult_notes', models.IntegerField(null=True)),
                ('ult_notes_nodata', models.BooleanField(null=True)),
                ('ult_notesdesigner', models.CharField(max_length=100, null=True)),
                ('ult_notesdesigner_nodata', models.BooleanField(null=True)),
                ('we_star', models.CharField(max_length=10, null=True)),
                ('we_kanji', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
