# Generated by Django 4.2.1 on 2024-07-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0005_songdatacn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdatacn',
            name='song_artist',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='song_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='song_reading',
            field=models.CharField(max_length=200),
        ),
    ]
