# Generated by Django 4.2.1 on 2025-02-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0006_alter_songdatacn_song_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongDataON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_official_id', models.CharField(max_length=10)),
                ('song_official_id_lunatic', models.CharField(blank=True, max_length=10, null=True)),
                ('song_name', models.CharField(max_length=200)),
                ('song_reading', models.CharField(max_length=200)),
                ('song_subname', models.CharField(blank=True, max_length=200, null=True)),
                ('song_subname_nodata', models.BooleanField(default=True)),
                ('song_artist', models.CharField(max_length=500)),
                ('song_genre', models.CharField(max_length=20)),
                ('song_bpm', models.IntegerField(blank=True, null=True)),
                ('song_bpm_nodata', models.BooleanField(default=True)),
                ('song_release', models.DateField(blank=True, null=True)),
                ('song_release_version', models.CharField(blank=True, max_length=20, null=True)),
                ('song_release_lunatic', models.DateField(blank=True, null=True)),
                ('song_release_lunatic_version', models.CharField(blank=True, max_length=20, null=True)),
                ('song_image_url', models.CharField(max_length=100)),
                ('song_fumen_id', models.CharField(blank=True, max_length=5, null=True)),
                ('character', models.CharField(max_length=100)),
                ('character_lunatic', models.CharField(blank=True, max_length=100, null=True)),
                ('is_bonus', models.BooleanField(default=False)),
                ('has_lunatic', models.BooleanField(default=False)),
                ('only_lunatic', models.BooleanField(default=False)),
                ('is_remaster', models.BooleanField(blank=True, null=True)),
                ('is_remaster_nodata', models.BooleanField(default=True)),
                ('exp_const', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('exp_const_nodata', models.BooleanField(default=True)),
                ('exp_notes', models.IntegerField(blank=True, null=True)),
                ('exp_notes_nodata', models.BooleanField(default=True)),
                ('exp_bell', models.IntegerField(blank=True, null=True)),
                ('exp_bell_nodata', models.BooleanField(default=True)),
                ('exp_notesdesigner', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_notesdesigner_nodata', models.BooleanField(default=True)),
                ('mas_const', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('mas_const_nodata', models.BooleanField(default=True)),
                ('mas_notes', models.IntegerField(blank=True, null=True)),
                ('mas_notes_nodata', models.BooleanField(default=True)),
                ('mas_bell', models.IntegerField(blank=True, null=True)),
                ('mas_bell_nodata', models.BooleanField(default=True)),
                ('mas_notesdesigner', models.CharField(blank=True, max_length=100, null=True)),
                ('mas_notesdesigner_nodata', models.BooleanField(default=True)),
                ('lun_const', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('lun_const_nodata', models.BooleanField(default=True)),
                ('lun_notes', models.IntegerField(blank=True, null=True)),
                ('lun_notes_nodata', models.BooleanField(default=True)),
                ('lun_bell', models.IntegerField(blank=True, null=True)),
                ('lun_bell_nodata', models.BooleanField(default=True)),
                ('lun_notesdesigner', models.CharField(blank=True, max_length=100, null=True)),
                ('lun_notesdesigner_nodata', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GameDataB2023',
        ),
        migrations.DeleteModel(
            name='SongDataC',
        ),
        migrations.DeleteModel(
            name='SongDataO',
        ),
        migrations.AddField(
            model_name='songdatacn',
            name='song_release_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='exp_const',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='exp_const_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='exp_notes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='exp_notes_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='exp_notesdesigner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='exp_notesdesigner_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='has_ultima',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='is_worldsend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='mas_const',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='mas_const_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='mas_notes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='mas_notes_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='mas_notesdesigner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='mas_notesdesigner_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='only_ultima',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='song_artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='song_bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='song_bpm_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='song_fumen_id',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='song_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='ult_const',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='ult_const_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='ult_notes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='ult_notes_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='ult_notesdesigner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='ult_notesdesigner_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='we_kanji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='we_star',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
