# Generated by Django 4.2.1 on 2025-03-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0007_songdataon_delete_gamedatab2023_delete_songdatac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdataon',
            name='song_release_lunatic_version',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='songdataon',
            name='song_release_version',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
