# Generated by Django 4.2.1 on 2025-03-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0008_alter_songdataon_song_release_lunatic_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdatacn',
            name='song_release_version',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
