# Generated by Django 4.2.1 on 2025-03-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0009_alter_songdatacn_song_release_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdatacn',
            name='adv_const',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='songdatacn',
            name='adv_const_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='songdatacn',
            name='bas_const',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='songdatacn',
            name='bas_const_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='songdatacn',
            name='song_namefolder_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songdatacn',
            name='song_namefolder_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='songdataon',
            name='adv_const',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='songdataon',
            name='adv_const_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='songdataon',
            name='bas_const',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='songdataon',
            name='bas_const_nodata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='songdatacn',
            name='song_release_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='songdataon',
            name='song_release_lunatic_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='songdataon',
            name='song_release_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
